"use strict";

exports.getContact = async () => {
	return {
		contactID: null,
		contactNumber: null,
		accountNumber: null,
		contactStatus: null,
		name: null,
		firstName: null,
		lastName: null,
		emailAddress: null,
		skypeUserName: null,
		contactPersons: null,
		bankAccountDetails: null,
		taxNumber: null,
		accountsReceivableTaxType: null,
		accountsPayableTaxType: null,
		addresses: null,
		phones: null,
		isSupplier: null,
		isCustomer: null,
		defaultCurrency: null,
		xeroNetworkKey: null,
		salesDefaultAccountCode: null,
		purchasesDefaultAccountCode: null,
		salesTrackingCategories: null,
		purchasesTrackingCategories: null,
		trackingCategoryName: null,
		trackingCategoryOption: null,
		paymentTerms: null,
		updatedDateUTC: null,
		contactGroups: null,
		website: null,
		brandingTheme: null,
		batchPayments: null,
		discount: null,
		balances: null,
		attachments: null,
		hasAttachments: null,
		validationErrors: null,
		hasValidationErrors: null,
		statusAttributeString: null,
	};
};
