"use strict";

module.exports = {
	SI: true,
	NO: false,

	// https://www.ibm.com/support/knowledgecenter/es/SSQP76_8.5.1/com.ibm.odm.dserver.events.ref/topics/ref_dse_restapi_responsecodes_errormsgs.html
	STATUS_200_OK: 200,
	STATUS_201_CREATED: 201,
	STATUS_202_ACCEPTED: 202,
	STATUS_204_NO_CONTENT: 204,

	STATUS_301_MOVED_PERMANENTLY: 301,
	STATUS_302_FOUND: 302,
	STATUS_303_SEE_OTHER: 303,
	STATUS_304_NOT_MODIFIED: 304,
	STATUS_307_TEMPORARY_REDIRECT: 307,

	STATUS_400_BAD_REQUEST: 400,
	STATUS_401_UNAUTHORIZED: 401,
	STATUS_403_FORBIDDEN: 403,
	STATUS_404_NOT_FOUND: 404,
	STATUS_405_METHOD_NOT_ALLOWED: 405,
	STATUS_406_NOT_ACCEPTABLE: 406,
	STATUS_412_PRECONDITION_FAILED: 412,
	STATUS_415_UNSUPPORTED_MEDIA_TYPE: 415,
	STATUS_500_INTERNAL_SERVER_ERROR: 500,
	STATUS_501_NOT_IMPLEMENTED: 501,

	PAGINATE_LIMIT: 1000,

	FILTER_DURATION_IN_DAYS: 861,
	FILTER_DURATION_IN_HOURS: 868,
	FILTER_COMPARASION_TYPE_BETWEEN: "Between",
	FILTER_COMPARASION_TYPE_EQUALS: "Equals",
	FILTER_COMPARASION_TYPE_GREATER_OR_EQUAL_THAN: "GreaterOrEqualThan",
	FILTER_NUMBER_OF_RESULTS: 100,
	FILTER_BY_ACTIVITIES: 115,

	FILTER_CUSTOM_ATRIBUTE: "CustomAttribute",

	ATTRIBUTE_TYPE_LOGICAL: "Logical",
	ATTRIBUTE_TYPE_TEXTUAL: "Textual",
	ATTRIBUTE_TYPE_NUMERIC: "Numeric",

	ATTRIBUTE_AUTHENTIC_BAMBA: 1006,
	ATTRIBUTE_DURATION_DD: 861,
	ATTRIBUTE_DURATION_HR: 868,
	ATTRIBUTE_PARENT_ID: 1003,
	ATTRIBUTE_DEPARTURE_POINT: 853,
	ATTRIBUTE_DEPARTURE_TIMES: 846,
	ATTRIBUTE_ARRIVAL_POINT: 852,
	ATTRIBUTE_DESCRIPTION: 133,
	ATTRIBUTE_PICKUP_INCLUDED: 916,
	ATTRIBUTE_DROPOFF_INCLUDED: 917,
	ATTRIBUTE_USER_SELECT_DEPARTURE_POINT: 1008,
	ATTRIBUTE_SERVICE_NAME: 121,
	ATTRIBUTE_NUMBER_OF_STARTS: 119,
	ATTRIBUTE_START_CITY_COUNTRY: 1028,
	ATTRIBUTE_END_CITY_COUNTRY: 1027,
	ATTRIBUTE_ACCOMODATION_TYPE: 1026,
	ATTRIBUTE_MEALS_SNACK: 995,
	ATTRIBUTE_CAPACITY: 120,
	ATTRIBUTE_MINUM_AGE: 978,
	ATTRIBUTE_AIRPORT_PICKUP_INCLUDED: 1004,
	ATTRIBUTE_PRIORITY: 198,
	ATTRIBUTE_LOCAL_PAYMENT: 10001,
	ATTRIBUTE_EASY: 827,
	ATTRIBUTE_MODERATE: 864,
	ATTRIBUTE_MILDLY_CHALLENGING: 864,
	ATTRIBUTE_CHALLENGING: 866,
	ATTRIBUTE_VERY_CHALLENGING: 867,
	ATTRIBUTE_SHOW_PRODUCT_B2B: 1013,
	ATTRIBUTE_SHOW_PRODUCT_B2C: 10003,
	ATTRIBUTE_DONT_SHOW_ROOMS_ON_THE_BOOKING_FORM: 176,
	ATTRIBUTE_SEARCH_PRIORITY: 198,
	ATTRIBUTE_MEALS_BREAKFAST: 114,
	ATTRIBUTE_MEALS_LUNCH: 162,
	ATTRIBUTE_MEALS_DINNER: 163,
	ATTRIBUTE_MEALS_SNACK: 995,

	SORT_BY_PRICE: "Price",
	SORT_BY_STARS: "Stars",
	SORT_BY_NAME: "Name",
	SORT_BY_DURATION: "Duration",
	SORT_BY_PRIORITY: "Priority",

	GROUP_NAME_SUB_CATEGORY: 320,
	GROUP_NAME_ACTIVITY_DEPARTURE_AND_ARRIBAL_INFO: 305,
	GROUP_NAME_SIMPLE_TOUR_DEPARTURE_AND_ARRIBAL_INFO: 318,
	GROUP_NAME_FIT_DEPARTURE_AND_ARRIBAL_INFO: 325,
	GROUP_NAME_MEALS: 43,
	GROUP_NAME_PHYSICAL_DEMAND: 56,
	GROUP_NAME_MAIN_THEME: 319,
	GROUP_NAME_NATURE_AND_ADVENTURE: 308,
	GROUP_NAME_MARINE: 313,
	GROUP_NAME_CULTURAL: 310,
	GROUP_NAME_FESTIVAL_AND_EVENTS: 314,
	GROUP_NAME_SPECIAL_INTERESTS: 315,
	GROUP_NAME_SELF_DRIVING: 321,
	GROUP_NAME_REGION: 311,

	GROUP_NAME_TRANSFER_TRANSPORTATION: 131,
	GROUP_NAME_TRANSFER_TRANSPORTATION_UNIT: 132,

	GROUP_NAME_LOCAL_PAYMENT: 10001,
	GROUP_NAME_PHYSICAL_DEMAND: 56,
	GROUP_NAME_BAMBA_RECOMMENDED: 323,

	INPRICE_TYPE_PERPERSON: "PerPerson",

	CONFIRM_AND_PAY_PAYMENT_METHOD_PAYPAL: "paypal",
	CONFIRM_AND_PAY_PAYMENT_METHOD_STRIPE: "stripe",
	CONFIRM_AND_PAY_ACCOUNT_TYPE_SUPER_ADMIN: "superadmin",
	CONFIRM_AND_PAY_ACCOUNT_TYPE_AGENT: "agent",
	CONFIRM_AND_PAY_ACCOUNT_TYPE_CLIENT: "client",

	DEFAULT_CURRENCY_ID: 840,
	DEFAULT_PAYMENT_METHOD_ID: 22,
	DEFAULT_INPRICE_TYPE: "Total",

	DEFAULT_FORMAT_DATE: "YYYY-MM-DD",

	TOUR_TYPE_SIMPLE_TOUR: 122,
	TOUR_TYPE_FIT_TOUR: 162,
	TOUR_TYPE_ACTIVITIES_TOUR: 115,

	TRAVEL_STYLE_GROUP_ADVENTURES: 7,
	TRAVEL_STYLE_CUSTOMIZABLE_INDEPENDENT_TRIP: 5,
	TRAVEL_STYLE_FLEXIBLE_TRAVEL_PASSES: 6,

	ACCOMODATION_CATEGORY_SHARED_TOUR: 16,
	ACCOMODATION_CATEGORY_PRIVATE_TOUR: 17,
	ACCOMODATION_CATEGORY_SELF_GUIDE_TOUR: 32,

	SERVICES_TYPE_BASIC: "Basic",
	SERVICES_TYPE_DISCOUNT: "Discount",
	SERVICES_PRICE_TYPE_FIXED: "Fixed",
	SERVICES_PRICE_TYPE_FIXED_DISCOUNT: "FixedDiscount",
	SERVICES_PRICE_TYPE_FIXED_PERCENTAGE: "Percentage",
	FILTER_DEFAULT_INPRICE_TYPE: "PerPerson",

	ACCOMODATION_TYPE_ACTIVITY_ID: 116,
	ACCOMODATION_TYPE_ACCOMODATION_ID: 116,

	SERVICE_TYPE_ADDITIONAL_SERVICE: "AdditionalService",
	SERVICE_TYPE_MANDATORY_SERVICES: "MandatoryService",
	SERVICE_TYPE_SUPLEMENTS: "Suplements",
	SERVICE_TYPE_SPECIAL_OFFER: "SpecialOffer",

	CUSTOMER_EMAIL: "test1@lemax.net",
	CUSTOMER_TYPE: 3,
	CUSTOMER_TYPE_PERSON: 0,
	CUSTOMER_TYPE_COMPANY: 1,
	CUSTOMER_CONTRACT_TYPE_ACCOUNT: 1,

	PASSENGER_DATE_OF_BIRTH: "1980-01-01",
	PASSENGER_CHILDREN_DATE_OF_BIRTH: "2013-01-01",
	PASSENGER_INFANT_DATE_OF_BIRTH: "2015-01-01",

	FAKE_CHILDREN_AGE: 5,

	CATEGORY_UNION_AIRPORT: 33,

	MIN_AGE: 0,
	MAX_AGE: 999,

	DOCUMENT_TYPE_ITINERARY: 8,
	DOCUMENT_TYPE_INVOICE: 3,

	NOTE_TYPE_CUPON: "COUPON",
	NOTE_TYPE_DISCOUNT: "DISCOUNT",
	NOTE_TYPE_ADDITIONAL_INFORMATION: "ADDITIONAL INFORMATION",
	NOTE_TYPE_IMPORTANT_INFORMATION: "IMPORTANT INFORMATION",

	TAILOR_MADE_CUSTOM_FIELD_94: 94,

	SYNC_PRICE_TYPE_INFANT: "Infant",
	SYNC_PRICE_TYPE_CHILD: "Child",
	SYNC_PRICE_TYPE_ADULT: "Adult",

	AVAILABILITY_STATUS_AVAILABLE: "Available",
	AVAILABILITY_STATUS_ON_REQUEST: "OnRequest",

	RESERVATION_STATUS_ID_ON_REQUEST: 1,
	RESERVATION_STATUS_ID_AVAILABILITY: 0,
	OUTPARAMETER_RESPONSE_DETAIL_DOS: 2,
	OUTPARAMETER_RESPONSE_DETAIL_TRES: 3,

	NUMBER_CHILDRENS_TOURS: 100,

	MAX_PHOTOS_GALLERY_FIT_TOUR: 2,

	COMPONENT_TYPE_ACCOMODATION: 1,
	COMPONENT_TYPE_ACTIVITY: 2,
	COMPONENT_TYPE_TRANSPORTATION: 3,
	COMPONENT_TYPE_SIMPLETOUR: 4,
	COMPONENT_TYPE_FREE_DAY: 5,

	CUSTOM_FIELD_OWNER_TYPE_RESERVATION: 1,
	CUSTOM_FIELD_MAJOR_REGION: 28,
	CUSTOM_FIELD_PACKAGE_TYPE: 43,
	CUSTOM_FIELD_TYPE_CERO: 0,
	CUSTOM_FIELD_AGENT_REFERENCE_NUMBER: 27,
	CUSTOM_FIELD_BAMBA_TOUR_ID: 71,
	CUSTOM_FIELD_BAMBA_TOUR_TYPE: 139,
	CUSTOM_FIELD_CREATED_BY: 95,
	CUSTOM_FIELD_BAMBA_REFERENCE_NUMBER: 96,
	CUSTOM_FIELD_BAMBA_RESERVATION_ID: 134,
	CUSTOM_FIELD_STA_PNR: 121,
	CUSTOM_FIELD_CONFIRM_AND_PAY_JSON: 140,
	CUSTOM_FIELD_CALCULATE_PRICE_JSON: 141,
	CUSTOM_FIELD_BRANCHOFFICE: 142,
	CUSTOM_FIELD_BRANCHOFFICENAME: 143,
	CUSTOM_FIELD_BOOKING_START_DESTINATION_COUNTRY: 147,

	// pro 148
	// test 146
	CUSTOM_FIELD_BOOKING_END_DATE: 146,

	// pro 149
	// test 148
	CUSTOM_FIELD_BOOKING_SERVICE_ID_MAIN_TOUR: 148,

	CUSTOM_FIELD_TYPE_TEXTBOX: 1,
	CUSTOM_FIELD_PASSENGER_NATIONALITY: 130,
	CUSTOM_FIELD_PASSENGER_NATIONALITY_MONGO: 131,
	CUSTOM_FIELD_PASSENGER_FIELD_NAME_NATIONALITY: "Nationality",
	CUSTOM_FIELD_PASSENGER_FIELD_NAME_NATIONALITY_MONGO: "Nationalitymongo",
	CUSTOM_FIELD_PASSENGER_GENDER: 132,
	CUSTOM_FIELD_PASSENGER_FIELD_NAME_GENDER: "Gender",
	CUSTOM_FIELD_PASSENGER_ID_REFERENCE: 144,
	CUSTOM_FIELD_PASSENGER_NAME_REFERENCE: "PassengerIDReference",

	CUSTOM_FIELD_TOTAL_GROSS_PRICE: 70,
	CUSTOM_FIELD_PURCHASE_DATE: 135,

	CUSTOM_FIELD_TOUR_TYPE: 139,
	CUSTOM_FIELD_TYPE_INPUT_FECHA: 6,

	BRANCH_OFFICE_TYPE_ONLINE_BOOKING_B2C: "Online booking (B2C)",
	BRANCH_OFFICE_TYPE_ONLINE_BOOKING_B2B: "Online booking (B2B)",

	BRANCH_OFFICE_SLUG_CENTRAL_OFFICE: "central-office",
	BRANCH_OFFICE_SLUG_ONLINE_BOOKING_B2C: "B2C",
	BRANCH_OFFICE_SLUG_ONLINE_BOOKING_B2B: "B2B",

	BRANCH_OFFICE_LEMAX_BOOKINGS_B2C_ID: 8,
	BRANCH_OFFICE_BOOKINGS_B2C_ID: 2,
	BRANCH_OFFICE_BOOKINGS_B2B_ID: 3,

	RESERVATION_STATUS_ID_INQUIRY: 1,
	RESERVATION_STATUS_ID_OPTION: 2,
	RESERVATION_STATUS_ID_CONFIRMED: 3,
	RESERVATION_STATUS_ID_FINISHED: 4,
	RESERVATION_STATUS_ID_UNREALIZED: 5,
	RESERVATION_STATUS_ID_CANCELLED: 6,
	RESERVATION_STATUS_ID_BOOKING: 7,
	RESERVATION_STATUS_ID_NOT_SYNC: 1000,
	RESERVATION_STATUS_ID_SYNC_IN_PROCESS: 1001,
	RESERVATION_STATUS_ID_SYNC_ERROR: 1002,
	RESERVATION_STATUS_ID_HIDDEN_RESERVATION_FOR_BOOKING_ADVANCED_TOUR_HOTEL_ITEMS: 8,
	RESERVATION_STATUS_ID_WAITING_LIST: 9,
	RESERVATION_STATUS_ID_WAITING_LIST_HIDDEN_RESERVATION_FOR_BOOKING_ADVANCED_TOUR_HOTEL_ITEMS: 10,
	RESERVATION_STATUS_ID_SHOPING_CART_CREATED_FROM_OB_FORM: 11,
	RESERVATION_STATUS_ID_TEMPLATE_RESERVATION: 12,

	RESERVATION_STATUS_TEXT_INQUIRY: "Inquiry",
	RESERVATION_STATUS_TEXT_OPTION: "Option",
	RESERVATION_STATUS_TEXT_CONFIRMED: "Confirmed",
	RESERVATION_STATUS_TEXT_FINISHED: "Finished",
	RESERVATION_STATUS_TEXT_UNREALIZED: "Unrealized",
	RESERVATION_STATUS_TEXT_CANCELLED: "Canceled",
	RESERVATION_STATUS_TEXT_WAITING_LIST: "OnHold",

	SENDING_BLUE_LIST_CLIENTS_ID: 25,

	DISCOUNT_TYPE_DISCOUNT: "DISCOUNT",
	DISCOUNT_TYPE_COUPON: "COUPON",
	DISCOUNT_TYPE_SPECIALOFFER: "SPECIALOFFER",

	TOUR_425: 425,
	DISPONIBILIDAD_TOUR_425_CRAWL: 50,

	BCRYPT_SALT_ROUNDS: 10,

	ACCOUNT_TYPE_SUPER_ADMINISTRATOR: "superadmin",
	ACCOUNT_TYPE_SUPER_AGENCIES: "superagency",
	ACCOUNT_TYPE_AGENCY: "agency",
	ACCOUNT_TYPE_STORE_MANAGER: "manager",
	ACCOUNT_TYPE_AGENT: "agent",

	ACCOUNT_TYPE_SUPER_ADMINISTRATOR_ID: "5d5c91508df0951ebcf28052",
	ACCOUNT_TYPE_SUPER_AGENCY_ID: "5daa5a4ef97cd415508b8364",
	ACCOUNT_TYPE_AGENCY_ID: "5d5c91688df0951ebcf28053",
	ACCOUNT_TYPE_STORE_MANAGER_ID: "5d5c91a48df0951ebcf28054",
	ACCOUNT_TYPE_AGENT_ID: "5d5c92198df0951ebcf28055",

	ACCOUNT_EMAIL_ADMINISTRATOR_DEFAULT: "marketing@bambatravel.com",
	ACCOUNT_LOGO_ADMINISTRATOR_DEFAULT: "assets/bamba/logo.png",

	FOLDER_TEMP: "./tmp/",
	FOLDER_AGENCY: "files/agency/",
	FOLDER_STORE: "files/store/",
	FOLDER_AGENT: "files/agent/",
	FOLDER_TOURS: "files/tours/",

	ACL_ACTION_TYPE_PRIVATE: "private",
	ACL_ACTION_TYPE_PUBLIC: "public",

	ACL_ACTION_TYPE_PRIVATE_ID: "5d52f21a078b3e12004f8f23",
	ACL_ACTION_TYPE_PUBLIC_ID: "5d52f21a078b3e12004f8f24",

	PASSENGER_DATA_PERSIST_MODE_DEFAULT: 2,
	PASSENGER_CREATE_CUSTOMER_FROM_PASSENGER: false,
	PASSENGER_SERVICES_NOT_VALID: "254",

	RESERVATION_CUSTOM_FIELD_ID_LIST_FOR_FETCHING: "27,28,43,121,95",
	BOOKINGS_TYPE_SYNC_PER_HOUR: "PerHour",
	BOOKINGS_TYPE_SYNC_MASIVE: "Masive",

	AVAILABILITY_TYPE_RELISE_PERIOD: "RELEASE PERIOD",
	AVAILABILITY_TYPE_INCA: "INCA",
	AVAILABILITY_TYPE_FREE_SALE: "FREESALE",
	AVAILABILITY_TYPE_ON_REQUEST: "ON REQUEST",

	RELEASE_PERIOD_SIMPLE_TOUR_DEFAULT: 45,
	RELEASE_PERIOD_ACTIVITY_DEFAULT: 2,

	SEQUENCES_TABLE_BAMBA_RESERVATION_ID: "bambareservationid",

	ADHOC_SERVICE_ADHOCSELLINGPRICE: 2414,
	ADHOC_SERVICE_ID: 254,

	AVIATOR_SUPPLIER_ID: "2000697",
	AVIATOR_API_KEY: "SQZ6hcK5K3LmAdAuUZaw5A7AqU5e06h-tH_DFM3tO4U",
	AVIATOR_REQUEST_TYPE_TOURLIST_REQUEST: "TourListRequest",
	AVIATOR_REQUEST_TYPE_AVAILABILITY_REQUEST: "AvailabilityRequest",
	AVIATOR_REQUEST_TYPE_BATCH_AVAILABILITY_REQUEST: "BatchAvailabilityRequest",
	AVIATOR_REQUEST_TYPE_BATCH_PRICING_REQUEST: "BatchPricingRequest",
	AVIATOR_REQUEST_TYPE_BOOKING_REQUEST: "BookingRequest",

	AVIATOR_REQUEST_TYPE_TOURLIST_RESPONSE: "TourListResponse",
	AVIATOR_REQUEST_TYPE_AVAILABILITY_RESPONSE: "AvailabilityResponse",
	AVIATOR_REQUEST_TYPE_BATCH_AVAILABILITY_RESPONSE: "BatchAvailabilityResponse",
	AVIATOR_REQUEST_TYPE_BATCH_PRICING_RESPONSE: "BatchPricingResponse",
	AVIATOR_REQUEST_TYPE_BOOKING_RESPONSE: "BookingResponse",

	AVIATOR_AVAILABILITY_FILTER_TRAVELER_SELECTS_PRODUCT_AND_DATE:
		"TRAVELER_SELECTS_PRODUCT_AND_DATE",
	AVIATOR_AVAILABILITY_FILTER_TRAVELER_SELECTS_PRODUCT_OPTIONS:
		"TRAVELER_SELECTS_PRODUCT_OPTIONS",
	AVIATOR_AVAILABILITY_FILTER_TRAVELED_PROCEDED_CHECKOUT:
		"TRAVELED_PROCEDED_CHECKOUT",

	AVIATOR_AGEBAND_ADULT: "Adult",
	AVIATOR_AGEBAND_CHILD: "Child",
	AVIATOR_AGEBAND_YOUTH: "Youth",
	AVIATOR_AGEBAND_INFANT: "Infant",
	AVIATOR_AGEBAND_SENIOR: "Senior",

	AVIATOR_DATE_BIRTH_ADULT_SENIOR: "20",
	AVIATOR_DATE_BIRTH_YOUTH_CHILD: "",
	AVIATOR_DATE_BIRTH_INFANT: "",

	AVIATOR_TRUE: "TRUE",
	AVIATOR_FALSE: "FALSE",
	AVIATOR_REQUEST_STATUS_ERROR: "ERROR",
	AVIATOR_REQUEST_STATUS_SUCCESS: "SUCCESS",
	AVIATOR_LANGUAGE_DEFAULT: "EN",
	AVIATOR_LANGUAGE_OPTION_DEFAULT: "GUIDE",

	AVIATOR_AVAILABILITY_STATUS_AVAILABLE: "AVAILABLE",
	AVIATOR_AVAILABILITY_STATUS_UNAVAILABLE: "UNAVAILABLE",

	AVIATOR_UNAVAILABILITY_REASON_SOLD_OUT: "SOLD_OUT",
	AVIATOR_UNAVAILABILITY_REASON_BLOCKED_OUT: "BLOCKED_OUT",
	AVIATOR_UNAVAILABILITY_REASON_INACTIVE: "INACTIVE",
	AVIATOR_UNAVAILABILITY_REASON_PAST_CUTOFF_DATE: "PAST_CUTOFF_DATE",
	AVIATOR_UNAVAILABILITY_REASON_TRAVELLER_MISMATCH: "TRAVELLER_MISMATCH",
	AVIATOR_UNAVAILABILITY_REASON_NO_EVENT: "NO_EVENT",
	AVIATOR_CURRENCY_CODE_DEFAULT: "USD",
	AVIATOR_SUPPLIER_DISCOUNT: 0.75,

	AVIATOR_EMAIL_DEFAULT_CLIENT_CONFIRM_AND_PAY: "compras@tripadvisor.com",
	AVIATOR_TRANSACTION_STATUS_CONFIRMED: "CONFIRMED",
	AVIATOR_TRANSACTION_STATUS_REJECTED: "REJECTED",
	AVIATOR_TRANSACTION_ERROR_TYPE_NOT_AVAILABILITY_DATE: "NOT_AVAILABILITY_DATE",
	AVIATOR_TRANSACTION_ERROR_TYPE_AVAILABILITY_ON_REQUEST:
		"AVAILABILITY_ON_REQUEST",
	AVIATOR_TRANSACTION_ERROR_REJECTION_REASON_NOT_OPERATING: "NOT_OPERATING",
	AVIATOR_TRANSACTION_ERROR_REJECTION_REASON_OTHER: "OTHER",

	AVIATOR_CUSTOMER_EMAIL_DEFAULT: "noreply@tripadvisor.com",
	AVIATOR_CUSTOMER_FULLNAME_DEFAULT: "TripAdvisor Online",
	AVIATOR_CUSTOMER_BIRTHDATE_DEFAULT: "1900-01-01",
	AVIATOR_CUSTOMER_NATIONALITY_DEFAULT: "5e0e741a22f7303a38447b86",
	AVIATOR_CUSTOMER_GENDER_DEFAULT: "M",
	AVIATOR_NATIONALITY_DEFAULT: "5e0e741a22f7303a38447b86",

	SYSTEM_ACTIVAR_DESCUENTOS_PARA_AGENTES: false,

	FILTER_NOT_FOUND: "ASIDHFAJDKNCABSDFKJAHDSFÑAJSHDFÑJAHSDKF",

	XERO_LINE_AMOUNT_TYPES_NO_TAX: "NoTax",
	XERO_STATUS_PAID: "PAID",
	XERO_STATUS_AUTHORISED: "AUTHORISED",

	XERO_TENTANT_ID: "7114124b-7a78-4d81-bbe0-f55f7796766c",

	XERO_BAMBA_TENANT_TYPE_BAMBA_ORGANISATION: "BAMBA_ORGANISATION",
	XERO_CURRENCY_USD: "USD",

	XERO_INVOICE_TYPE_DEFAULT: "ACCREC",

	XERO_INVOICE_STATUS_DRAFT: "DRAFT",
	XERO_INVOICE_STATUS_SUBMITTED: "SUBMITTED",
	XERO_INVOICE_STATUS_DELETED: "DELETED",
	XERO_INVOICE_STATUS_AUTHORISED: "AUTHORISED",
	XERO_INVOICE_STATUS_PAID: "PAID",
	XERO_INVOICE_STATUS_VOIDED: "VOIDED",

	XERO_ACCOUNT_COST_OF_GOODS_SOLD: 310,
	XERO_ACCOUNT_COST_OF_GOODS_SOLDS_COMMISION: 1000,
	XERO_ACCOUNT_SALES_DISCCOUNTS: 1001,
};
